### ISSUE TITLE
Upload old charts to GitHub releases

### ISSUE THREAD

**Issue by felipecrs** [scottrigby/helm-adopt-package-history#3]
This is awesome, but I wonder if it would be a better idea to upload the previous charts as GitHub Releases instead, to prevent binaries from being added to git, and thus making the repo bigger.

**Comment by scottrigby** [comment]
Hi just saw this issue. Agreed that would have been ideal. In the case of helm/stable and helm/incubator migration, the GitHub pages team sponsored hosting. This was required because these were very heavily used Helm repos. If we had sponsorship from GitHub to do this with GH releases, we would have used https://github.com/helm/chart-releaser for the upload process. Thanks!

Check out this Helm blog post for more details https://helm.sh/blog/new-location-stable-incubator-charts/. And thanks again!
